create table if not exists public.recruitment_notices (
  id bigint generated by default as identity primary key,
  title text not null,
  excerpt text not null default '',
  aggregator_url text not null unique,
  official_url text,
  source_name text not null,
  province text,
  recruitment_type text,
  published_at timestamptz,
  content_hash text unique,
  is_published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists recruitment_notices_published_at_idx on public.recruitment_notices (published_at);
create index if not exists recruitment_notices_province_idx on public.recruitment_notices (province);
create index if not exists recruitment_notices_recruitment_type_idx on public.recruitment_notices (recruitment_type);
create index if not exists recruitment_notices_content_hash_idx on public.recruitment_notices (content_hash);
